version: "3"
containers:
- name: vsc-ide
  image: codercom/code-server
  cmd: code-server workspace /root/create-daml-app --user-data-dir /user-data --auth
    none --disable-telemetry
  shell: bash
  ports:
  - 80
  - 3000
  - 6865
  - 7575
  - 7557
  - 8080
  memory: 2048
